#version: '3.8'
#
#services:
#  ai-api:
#    build: .
#    ports:
#      - "8000:8000"
#    environment:
#      - PYTHONPATH=/app
#    volumes:
#      - ./models:/app/models
#    restart: unless-stopped

version: '3.8'

services:
  wrool-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WROOL_USE_GPU=true
      - WROOL_LOG_LEVEL=INFO
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
